/**
 * Cabeceras de seguridad de las respuestas que genera el WORKER.
 *
 * POR QUÉ ESTO EXISTE HABIENDO UN `public/_headers`:
 * con Workers Static Assets, la petición que casa con un fichero del bundle la
 * sirve la capa de assets SIN invocar al Worker — y ahí manda `_headers`. La
 * que NO casa la resuelve el Worker, y a esa `_headers` no la toca. Cloudflare
 * lo dice explícitamente:
 *
 *   «Custom headers defined in the `_headers` file are not applied to responses
 *    generated by your Worker code, even if the request URL matches a rule
 *    defined in `_headers`.»
 *   — developers.cloudflare.com/workers/static-assets/headers/
 *
 * O sea que hay DOS listas y las dos hacen falta. Un `_headers` a solas PARECE
 * cubrir el site entero y cubre la mitad: se puede leer y dar el trabajo por
 * hecho. En esta plantilla las rutas que salen por el Worker son las landings
 * `/lp/[slug]` (`prerender = false`) y los 404 — o sea, justo por donde entra el
 * tráfico de campaña.
 *
 * **Las dos listas se mantienen A LA PAR.** Si aquí se añade una cabecera, va
 * también a `public/_headers`, y al revés. Se comprueba RUTA POR RUTA con
 * `curl -sI`: `/`, una landing `/lp/*` y un 404.
 */

export const SECURITY_HEADERS: Record<string, string> = {
  // No adivines el tipo: sirve lo que dice Content-Type y nada más.
  'X-Content-Type-Options': 'nosniff',

  // Al salir a un tercero solo viaja el origen, y solo si sigue siendo HTTPS.
  'Referrer-Policy': 'strict-origin-when-cross-origin',

  // SAMEORIGIN y no DENY a propósito: el editor visual del Hub enseña estos
  // sites dentro de un iframe a través de `hub.preview-proxy`, que resirve el
  // HTML desde su propio origen. `DENY` rompe hasta el encuadre del mismo
  // origen, y SAMEORIGIN es lo que ya servían los assets sin romper nada.
  'X-Frame-Options': 'SAMEORIGIN',

  // El equivalente moderno de la línea de arriba. Deliberadamente SOLO
  // `frame-ancestors`: una CSP con `script-src` hay que medirla contra el
  // bundle que sirve cada site —analítica, beacons, formularios, fuentes,
  // mapas—, y aflojarla a ciegas con `'unsafe-inline'` para que «no rompa»
  // sería poner una decoración con forma de control. Si un descendiente
  // necesita `script-src`, que la mida y la ponga él.
  'Content-Security-Policy': "frame-ancestors 'self'",

  // Nada de cámara, micrófono ni geolocalización: la plantilla no los usa. El
  // site que necesite uno lo abre aquí, y sabiendo por qué.
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',

  // OJO: aquí NO se declara `Strict-Transport-Security`, y es deliberado.
  // Si la zona ya manda un HSTS con `includeSubDomains`, esta lista lo PISARÍA
  // a la baja al declararlo sin él: sería un recorte de la política, no una
  // mejora. Antes de añadirlo, mira con `curl -sI` qué HSTS llega ya al
  // dominio; si no llega ninguno, el sitio donde ponerlo es la configuración
  // de zona, no aquí.
}

/**
 * Las escribe sin pisar lo que ya venga puesto: si algún día una ruta necesita
 * su propia CSP, la pone ella y esto no la machaca.
 */
export function applySecurityHeaders(headers: Headers): void {
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    if (!headers.has(name)) headers.set(name, value)
  }
}
